name: fsauce_vendor_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  dio: ^5.4.3+1
  google_fonts: ^6.2.1
  new_version_plus: ^0.0.11
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  encrypt: ^5.0.3
  tuple: ^2.0.2
  crypto: ^3.0.3
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  firebase_auth: ^4.2.2
  flutter_facebook_auth: ^6.0.4
  stacked_firebase_auth: ^2.19.2
  firebase_core: ^2.10.0
  easy_stepper: ^0.8.5
  dotted_border: ^2.0.0
  r_dotted_line_border: ^0.1.1
  flutter_hsvcolor_picker: ^1.5.0
  flutter_rating_bar: ^4.0.1
  qr_code_scanner: ^1.0.1
  image_picker: ^1.1.2
  multi_select_flutter: ^4.1.3
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  video_player: ^2.9.1
  geolocator: ^12.0.0
  flutter_stripe: ^10.0.0
  intl: ^0.19.0
  custom_syncfusion_flutter_charts: ^1.0.1
dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.2.0
flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/pngs/
    - assets/svgs/app_icon.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/pngs/fsauce_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
