///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AllPlanModelData {
/*
{
  "_id": "6938291815c8fe52bb0824ec",
  "title": "Platinum Plan",
  "billedFrequency": "yearly",
  "planType": "subscribers",
  "price": 300,
  "features": [
    "Access to basic analytics"
  ],
  "stripeProdutId": "prod_TZaTZBXL8E4OHi",
  "stripePriceId": "price_1ScRJ2KlUbZkAAt6z9yOqUhE",
  "isActive": true,
  "createdAt": "2025-12-09T13:50:16.980Z",
  "updatedAt": "2025-12-09T13:50:16.980Z"
}
*/

  String? Id;
  String? title;
  String? billedFrequency;
  String? planType;
  int? price;
  List<String?>? features;
  String? stripeProdutId;
  String? stripePriceId;
  bool? isActive;
  String? createdAt;
  String? updatedAt;

  AllPlanModelData({
    this.Id,
    this.title,
    this.billedFrequency,
    this.planType,
    this.price,
    this.features,
    this.stripeProdutId,
    this.stripePriceId,
    this.isActive,
    this.createdAt,
    this.updatedAt,
  });
  AllPlanModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    title = json['title']?.toString();
    billedFrequency = json['billedFrequency']?.toString();
    planType = json['planType']?.toString();
    price = json['price']?.toInt();
    if (json['features'] != null) {
      final v = json['features'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      features = arr0;
    }
    stripeProdutId = json['stripeProdutId']?.toString();
    stripePriceId = json['stripePriceId']?.toString();
    isActive = json['isActive'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['title'] = title;
    data['billedFrequency'] = billedFrequency;
    data['planType'] = planType;
    data['price'] = price;
    if (features != null) {
      final v = features;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['features'] = arr0;
    }
    data['stripeProdutId'] = stripeProdutId;
    data['stripePriceId'] = stripePriceId;
    data['isActive'] = isActive;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class AllPlanModel {
/*
{
  "status": true,
  "message": "Subscription plans list",
  "data": [
    {
      "_id": "6938291815c8fe52bb0824ec",
      "title": "Platinum Plan",
      "billedFrequency": "yearly",
      "planType": "subscribers",
      "price": 300,
      "features": [
        "Access to basic analytics"
      ],
      "stripeProdutId": "prod_TZaTZBXL8E4OHi",
      "stripePriceId": "price_1ScRJ2KlUbZkAAt6z9yOqUhE",
      "isActive": true,
      "createdAt": "2025-12-09T13:50:16.980Z",
      "updatedAt": "2025-12-09T13:50:16.980Z"
    }
  ]
}
*/

  bool? status;
  String? message;
  List<AllPlanModelData>? data;

  AllPlanModel({
    this.status,
    this.message,
    this.data,
  });
  AllPlanModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <AllPlanModelData>[];
      v.forEach((v) {
        arr0.add(AllPlanModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
