///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DashboardYearlyDataCouponCounts {
/*
{
  "month": "Jan",
  "total": 0,
  "order": "01"
}
*/

  String? month;
  int? total;
  String? order;

  DashboardYearlyDataCouponCounts({
    this.month,
    this.total,
    this.order,
  });
  DashboardYearlyDataCouponCounts.fromJson(Map<String, dynamic> json) {
    month = json['month']?.toString();
    total = json['total']?.toInt();
    order = json['order']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['month'] = month;
    data['total'] = total;
    data['order'] = order;
    return data;
  }
}

class DashboardYearlyDataRewardsCount {
/*
{
  "month": "Jan",
  "total": 0,
  "order": "01"
}
*/

  String? month;
  int? total;
  String? order;

  DashboardYearlyDataRewardsCount({
    this.month,
    this.total,
    this.order,
  });
  DashboardYearlyDataRewardsCount.fromJson(Map<String, dynamic> json) {
    month = json['month']?.toString();
    total = json['total']?.toInt();
    order = json['order']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['month'] = month;
    data['total'] = total;
    data['order'] = order;
    return data;
  }
}

class DashboardYearlyDataRedemptionsCount {
/*
{
  "month": "Jan",
  "total": 0,
  "order": "01"
}
*/

  String? month;
  int? total;
  String? order;

  DashboardYearlyDataRedemptionsCount({
    this.month,
    this.total,
    this.order,
  });
  DashboardYearlyDataRedemptionsCount.fromJson(Map<String, dynamic> json) {
    month = json['month']?.toString();
    total = json['total']?.toInt();
    order = json['order']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['month'] = month;
    data['total'] = total;
    data['order'] = order;
    return data;
  }
}

class DashboardYearlyDataCards {
/*
{
  "totalStamps": 3,
  "totalCoupons": 0,
  "totalRewards": 0
}
*/

  int? totalStamps;
  int? totalCoupons;
  int? totalRewards;

  DashboardYearlyDataCards({
    this.totalStamps,
    this.totalCoupons,
    this.totalRewards,
  });
  DashboardYearlyDataCards.fromJson(Map<String, dynamic> json) {
    totalStamps = json['totalStamps']?.toInt();
    totalCoupons = json['totalCoupons']?.toInt();
    totalRewards = json['totalRewards']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['totalStamps'] = totalStamps;
    data['totalCoupons'] = totalCoupons;
    data['totalRewards'] = totalRewards;
    return data;
  }
}

class DashboardYearlyData {
/*
{
  "cards": {
    "totalStamps": 3,
    "totalCoupons": 0,
    "totalRewards": 0
  },
  "redemptionsCount": [
    {
      "month": "Jan",
      "total": 0,
      "order": "01"
    }
  ],
  "rewardsCount": [
    {
      "month": "Jan",
      "total": 0,
      "order": "01"
    }
  ],
  "couponCounts": [
    {
      "month": "Jan",
      "total": 0,
      "order": "01"
    }
  ]
}
*/

  DashboardYearlyDataCards? cards;
  List<DashboardYearlyDataRedemptionsCount?>? redemptionsCount;
  List<DashboardYearlyDataRewardsCount?>? rewardsCount;
  List<DashboardYearlyDataCouponCounts?>? couponCounts;

  DashboardYearlyData({
    this.cards,
    this.redemptionsCount,
    this.rewardsCount,
    this.couponCounts,
  });
  DashboardYearlyData.fromJson(Map<String, dynamic> json) {
    cards = (json['cards'] != null) ? DashboardYearlyDataCards.fromJson(json['cards']) : null;
    if (json['redemptionsCount'] != null) {
      final v = json['redemptionsCount'];
      final arr0 = <DashboardYearlyDataRedemptionsCount>[];
      v.forEach((v) {
        arr0.add(DashboardYearlyDataRedemptionsCount.fromJson(v));
      });
      redemptionsCount = arr0;
    }
    if (json['rewardsCount'] != null) {
      final v = json['rewardsCount'];
      final arr0 = <DashboardYearlyDataRewardsCount>[];
      v.forEach((v) {
        arr0.add(DashboardYearlyDataRewardsCount.fromJson(v));
      });
      rewardsCount = arr0;
    }
    if (json['couponCounts'] != null) {
      final v = json['couponCounts'];
      final arr0 = <DashboardYearlyDataCouponCounts>[];
      v.forEach((v) {
        arr0.add(DashboardYearlyDataCouponCounts.fromJson(v));
      });
      couponCounts = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (cards != null) {
      data['cards'] = cards!.toJson();
    }
    if (redemptionsCount != null) {
      final v = redemptionsCount;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['redemptionsCount'] = arr0;
    }
    if (rewardsCount != null) {
      final v = rewardsCount;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['rewardsCount'] = arr0;
    }
    if (couponCounts != null) {
      final v = couponCounts;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['couponCounts'] = arr0;
    }
    return data;
  }
}
