///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DashboardWeeklyDataCouponCounts {
/*
{
  "date": "Mon",
  "total": 0
}
*/

  String? date;
  int? total;

  DashboardWeeklyDataCouponCounts({
    this.date,
    this.total,
  });
  DashboardWeeklyDataCouponCounts.fromJson(Map<String, dynamic> json) {
    date = json['date']?.toString();
    total = json['total']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['date'] = date;
    data['total'] = total;
    return data;
  }
}

class DashboardWeeklyDataRewardsCount {
/*
{
  "date": "Mon",
  "total": 0
}
*/

  String? date;
  int? total;

  DashboardWeeklyDataRewardsCount({
    this.date,
    this.total,
  });
  DashboardWeeklyDataRewardsCount.fromJson(Map<String, dynamic> json) {
    date = json['date']?.toString();
    total = json['total']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['date'] = date;
    data['total'] = total;
    return data;
  }
}

class DashboardWeeklyDataRedemptionsCount {
/*
{
  "date": "Mon",
  "total": 0
}
*/

  String? date;
  int? total;

  DashboardWeeklyDataRedemptionsCount({
    this.date,
    this.total,
  });
  DashboardWeeklyDataRedemptionsCount.fromJson(Map<String, dynamic> json) {
    date = json['date']?.toString();
    total = json['total']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['date'] = date;
    data['total'] = total;
    return data;
  }
}

class DashboardWeeklyDataCards {
/*
{
  "totalStamps": 3,
  "totalCoupons": 0,
  "totalRewards": 0
}
*/

  int? totalStamps;
  int? totalCoupons;
  int? totalRewards;

  DashboardWeeklyDataCards({
    this.totalStamps,
    this.totalCoupons,
    this.totalRewards,
  });
  DashboardWeeklyDataCards.fromJson(Map<String, dynamic> json) {
    totalStamps = json['totalStamps']?.toInt();
    totalCoupons = json['totalCoupons']?.toInt();
    totalRewards = json['totalRewards']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['totalStamps'] = totalStamps;
    data['totalCoupons'] = totalCoupons;
    data['totalRewards'] = totalRewards;
    return data;
  }
}

class DashboardWeeklyData {
/*
{
  "cards": {
    "totalStamps": 3,
    "totalCoupons": 0,
    "totalRewards": 0
  },
  "redemptionsCount": [
    {
      "date": "Mon",
      "total": 0
    }
  ],
  "rewardsCount": [
    {
      "date": "Mon",
      "total": 0
    }
  ],
  "couponCounts": [
    {
      "date": "Mon",
      "total": 0
    }
  ]
}
*/

  DashboardWeeklyDataCards? cards;
  List<DashboardWeeklyDataRedemptionsCount?>? redemptionsCount;
  List<DashboardWeeklyDataRewardsCount?>? rewardsCount;
  List<DashboardWeeklyDataCouponCounts?>? couponCounts;

  DashboardWeeklyData({
    this.cards,
    this.redemptionsCount,
    this.rewardsCount,
    this.couponCounts,
  });
  DashboardWeeklyData.fromJson(Map<String, dynamic> json) {
    cards = (json['cards'] != null) ? DashboardWeeklyDataCards.fromJson(json['cards']) : null;
    if (json['redemptionsCount'] != null) {
      final v = json['redemptionsCount'];
      final arr0 = <DashboardWeeklyDataRedemptionsCount>[];
      v.forEach((v) {
        arr0.add(DashboardWeeklyDataRedemptionsCount.fromJson(v));
      });
      redemptionsCount = arr0;
    }
    if (json['rewardsCount'] != null) {
      final v = json['rewardsCount'];
      final arr0 = <DashboardWeeklyDataRewardsCount>[];
      v.forEach((v) {
        arr0.add(DashboardWeeklyDataRewardsCount.fromJson(v));
      });
      rewardsCount = arr0;
    }
    if (json['couponCounts'] != null) {
      final v = json['couponCounts'];
      final arr0 = <DashboardWeeklyDataCouponCounts>[];
      v.forEach((v) {
        arr0.add(DashboardWeeklyDataCouponCounts.fromJson(v));
      });
      couponCounts = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (cards != null) {
      data['cards'] = cards!.toJson();
    }
    if (redemptionsCount != null) {
      final v = redemptionsCount;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['redemptionsCount'] = arr0;
    }
    if (rewardsCount != null) {
      final v = rewardsCount;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['rewardsCount'] = arr0;
    }
    if (couponCounts != null) {
      final v = couponCounts;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['couponCounts'] = arr0;
    }
    return data;
  }
}
