///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DashboardDataCouponCountsGraphData {
/*
{
  "week": "Tue Jun 25 - Mon Jul 01",
  "count": 0
}
*/

  String? week;
  int? count;

  DashboardDataCouponCountsGraphData({
    this.week,
    this.count,
  });
  DashboardDataCouponCountsGraphData.fromJson(Map<String, dynamic> json) {
    week = json['week']?.toString();
    count = json['count']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['week'] = week;
    data['count'] = count;
    return data;
  }
}

class DashboardDataCouponCounts {
/*
{
  "graphData": [
    {
      "week": "Tue Jun 25 - Mon Jul 01",
      "count": 0
    }
  ]
}
*/

  List<DashboardDataCouponCountsGraphData?>? graphData;

  DashboardDataCouponCounts({
    this.graphData,
  });
  DashboardDataCouponCounts.fromJson(Map<String, dynamic> json) {
    if (json['graphData'] != null) {
      final v = json['graphData'];
      final arr0 = <DashboardDataCouponCountsGraphData>[];
      v.forEach((v) {
        arr0.add(DashboardDataCouponCountsGraphData.fromJson(v));
      });
      graphData = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (graphData != null) {
      final v = graphData;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['graphData'] = arr0;
    }
    return data;
  }
}

class DashboardDataRewardsCountGraphData {
/*
{
  "week": "Tue Jun 25 - Mon Jul 01",
  "count": 0
}
*/

  String? week;
  int? count;

  DashboardDataRewardsCountGraphData({
    this.week,
    this.count,
  });
  DashboardDataRewardsCountGraphData.fromJson(Map<String, dynamic> json) {
    week = json['week']?.toString();
    count = json['count']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['week'] = week;
    data['count'] = count;
    return data;
  }
}

class DashboardDataRewardsCount {
/*
{
  "graphData": [
    {
      "week": "Tue Jun 25 - Mon Jul 01",
      "count": 0
    }
  ]
}
*/

  List<DashboardDataRewardsCountGraphData?>? graphData;

  DashboardDataRewardsCount({
    this.graphData,
  });
  DashboardDataRewardsCount.fromJson(Map<String, dynamic> json) {
    if (json['graphData'] != null) {
      final v = json['graphData'];
      final arr0 = <DashboardDataRewardsCountGraphData>[];
      v.forEach((v) {
        arr0.add(DashboardDataRewardsCountGraphData.fromJson(v));
      });
      graphData = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (graphData != null) {
      final v = graphData;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['graphData'] = arr0;
    }
    return data;
  }
}

class DashboardDataRedemptionsCountGraphData {
/*
{
  "week": "Tue Jun 25 - Mon Jul 01",
  "count": 0
}
*/

  String? week;
  int? count;

  DashboardDataRedemptionsCountGraphData({
    this.week,
    this.count,
  });
  DashboardDataRedemptionsCountGraphData.fromJson(Map<String, dynamic> json) {
    week = json['week']?.toString();
    count = json['count']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['week'] = week;
    data['count'] = count;
    return data;
  }
}

class DashboardDataRedemptionsCount {
/*
{
  "graphData": [
    {
      "week": "Tue Jun 25 - Mon Jul 01",
      "count": 0
    }
  ]
}
*/

  List<DashboardDataRedemptionsCountGraphData?>? graphData;

  DashboardDataRedemptionsCount({
    this.graphData,
  });
  DashboardDataRedemptionsCount.fromJson(Map<String, dynamic> json) {
    if (json['graphData'] != null) {
      final v = json['graphData'];
      final arr0 = <DashboardDataRedemptionsCountGraphData>[];
      v.forEach((v) {
        arr0.add(DashboardDataRedemptionsCountGraphData.fromJson(v));
      });
      graphData = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (graphData != null) {
      final v = graphData;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['graphData'] = arr0;
    }
    return data;
  }
}

class DashboardDataCards {
/*
{
  "totalStamps": 3,
  "totalCoupons": 0,
  "totalRewards": 0
}
*/

  int? totalStamps;
  int? totalCoupons;
  int? totalRewards;

  DashboardDataCards({
    this.totalStamps,
    this.totalCoupons,
    this.totalRewards,
  });
  DashboardDataCards.fromJson(Map<String, dynamic> json) {
    totalStamps = json['totalStamps']?.toInt();
    totalCoupons = json['totalCoupons']?.toInt();
    totalRewards = json['totalRewards']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['totalStamps'] = totalStamps;
    data['totalCoupons'] = totalCoupons;
    data['totalRewards'] = totalRewards;
    return data;
  }
}

class DashboardData {
/*
{
  "cards": {
    "totalStamps": 3,
    "totalCoupons": 0,
    "totalRewards": 0
  },
  "redemptionsCount": {
    "graphData": [
      {
        "week": "Tue Jun 25 - Mon Jul 01",
        "count": 0
      }
    ]
  },
  "rewardsCount": {
    "graphData": [
      {
        "week": "Tue Jun 25 - Mon Jul 01",
        "count": 0
      }
    ]
  },
  "couponCounts": {
    "graphData": [
      {
        "week": "Tue Jun 25 - Mon Jul 01",
        "count": 0
      }
    ]
  }
}
*/

  DashboardDataCards? cards;
  DashboardDataRedemptionsCount? redemptionsCount;
  DashboardDataRewardsCount? rewardsCount;
  DashboardDataCouponCounts? couponCounts;

  DashboardData({
    this.cards,
    this.redemptionsCount,
    this.rewardsCount,
    this.couponCounts,
  });
  DashboardData.fromJson(Map<String, dynamic> json) {
    cards = (json['cards'] != null) ? DashboardDataCards.fromJson(json['cards']) : null;
    redemptionsCount = (json['redemptionsCount'] != null) ? DashboardDataRedemptionsCount.fromJson(json['redemptionsCount']) : null;
    rewardsCount = (json['rewardsCount'] != null) ? DashboardDataRewardsCount.fromJson(json['rewardsCount']) : null;
    couponCounts = (json['couponCounts'] != null) ? DashboardDataCouponCounts.fromJson(json['couponCounts']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (cards != null) {
      data['cards'] = cards!.toJson();
    }
    if (redemptionsCount != null) {
      data['redemptionsCount'] = redemptionsCount!.toJson();
    }
    if (rewardsCount != null) {
      data['rewardsCount'] = rewardsCount!.toJson();
    }
    if (couponCounts != null) {
      data['couponCounts'] = couponCounts!.toJson();
    }
    return data;
  }
}
