///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoyaltyCardModel {
/*
{
  "title": "Buy 5 Get 1 Free",
  "noOfStamps": 4,
  "cardBackgroundColor": "#0078AE",
  "cardTextColor": "#0078AE",
  "stampBackgroundColor": "#0078AE",
  "stampColor": "#0078AE",
  "isActive": true,
  "vendor": "66728075a065bac72ace0f09",
  "_id": "66793fabd3ca02751fdb1ed6"
}
*/

  String title;
  int noOfStamps;
  String cardBackgroundColor;
  String cardTextColor;
  String stampBackgroundColor;
  String stampColor;
  bool isActive;
  String vendor;
  String Id;

  LoyaltyCardModel({
    required this.title,
    required this.noOfStamps,
    required this.cardBackgroundColor,
    required this.cardTextColor,
    required this.stampBackgroundColor,
    required this.stampColor,
    required this.isActive,
    required this.vendor,
    required this.Id,
  });

  factory LoyaltyCardModel.fromJson(Map<String, dynamic> json) {
    return LoyaltyCardModel(
        title: json['title'],
        noOfStamps: json['noOfStamps'],
        cardBackgroundColor: json['cardBackgroundColor'],
        cardTextColor: json['cardTextColor'],
        stampBackgroundColor: json['stampBackgroundColor'],
        stampColor: json['stampColor'],
        isActive: json['isActive'],
        vendor: json['vendor'],
        Id: json['_id']);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['noOfStamps'] = noOfStamps;
    data['cardBackgroundColor'] = cardBackgroundColor;
    data['cardTextColor'] = cardTextColor;
    data['stampBackgroundColor'] = stampBackgroundColor;
    data['stampColor'] = stampColor;
    data['isActive'] = isActive;
    data['vendor'] = vendor;
    data['_id'] = Id;
    return data;
  }
}
