///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoyaltyModelDataVendor {
/*
{
  "_id": "692ee35ba8f4355c9b641236",
  "restaurantName": "Happy",
  "restaurantLogo": "https://foodsauciety.s3.amazonaws.com/foodsauciety-gallery-1765286196749-scaled_1578f2a4-aada-42da-8faf-bbd64010e3c6649063088243167624.jpg"
}
*/

  String? Id;
  String? restaurantName;
  String? restaurantLogo;

  LoyaltyModelDataVendor({
    this.Id,
    this.restaurantName,
    this.restaurantLogo,
  });
  LoyaltyModelDataVendor.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    restaurantName = json['restaurantName']?.toString();
    restaurantLogo = json['restaurantLogo']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['restaurantName'] = restaurantName;
    data['restaurantLogo'] = restaurantLogo;
    return data;
  }
}

class LoyaltyModelData {
/*
{
  "_id": "693a5650d09d0a8e99906823",
  "user": "68f21976a3a6d3630e757c18",
  "loyaltyCard": "69158ca8295a3f853325667b",
  "vendor": {
    "_id": "692ee35ba8f4355c9b641236",
    "restaurantName": "Happy",
    "restaurantLogo": "https://foodsauciety.s3.amazonaws.com/foodsauciety-gallery-1765286196749-scaled_1578f2a4-aada-42da-8faf-bbd64010e3c6649063088243167624.jpg"
  },
  "rewardCount": 1,
  "createdAt": "2025-12-11T05:27:44.097Z",
  "updatedAt": "2025-12-11T05:27:44.097Z",
  "typeOfRedeem": "stamps"
}
*/

  String? Id;
  String? user;
  String? loyaltyCard;
  LoyaltyModelDataVendor? vendor;
  int? rewardCount;
  String? createdAt;
  String? updatedAt;
  String? typeOfRedeem;

  LoyaltyModelData({
    this.Id,
    this.user,
    this.loyaltyCard,
    this.vendor,
    this.rewardCount,
    this.createdAt,
    this.updatedAt,
    this.typeOfRedeem,
  });
  LoyaltyModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    user = json['user']?.toString();
    loyaltyCard = json['loyaltyCard']?.toString();
    vendor = (json['vendor'] != null) ? LoyaltyModelDataVendor.fromJson(json['vendor']) : null;
    rewardCount = json['rewardCount']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    typeOfRedeem = json['typeOfRedeem']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['user'] = user;
    data['loyaltyCard'] = loyaltyCard;
    if (vendor != null) {
      data['vendor'] = vendor!.toJson();
    }
    data['rewardCount'] = rewardCount;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['typeOfRedeem'] = typeOfRedeem;
    return data;
  }
}

class LoyaltyModel {
/*
{
  "status": true,
  "message": "Loyalty Scan Stats",
  "data": [
    {
      "_id": "693a5650d09d0a8e99906823",
      "user": "68f21976a3a6d3630e757c18",
      "loyaltyCard": "69158ca8295a3f853325667b",
      "vendor": {
        "_id": "692ee35ba8f4355c9b641236",
        "restaurantName": "Happy",
        "restaurantLogo": "https://foodsauciety.s3.amazonaws.com/foodsauciety-gallery-1765286196749-scaled_1578f2a4-aada-42da-8faf-bbd64010e3c6649063088243167624.jpg"
      },
      "rewardCount": 1,
      "createdAt": "2025-12-11T05:27:44.097Z",
      "updatedAt": "2025-12-11T05:27:44.097Z",
      "typeOfRedeem": "stamps"
    }
  ]
}
*/

  bool? status;
  String? message;
  List<LoyaltyModelData>? data;

  LoyaltyModel({
    this.status,
    this.message,
    this.data,
  });
  LoyaltyModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <LoyaltyModelData>[];
      v.forEach((v) {
        arr0.add(LoyaltyModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
