///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NotificationModel {
/*
{
  "_id": "692ec7f2b075605817a2f95e",
  "receiver": "vendors",
  "title": "Notification from food Sauciety",
  "body": "Grab offers with more 10% in nearby resturants",
  "createdAt": "2025-12-02T11:05:22.067Z"
}
*/

  String? Id;
  String? receiver;
  String? title;
  String? body;
  String? createdAt;

  NotificationModel({
    this.Id,
    this.receiver,
    this.title,
    this.body,
    this.createdAt,
  });
  NotificationModel.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    receiver = json['receiver']?.toString();
    title = json['title']?.toString();
    body = json['body']?.toString();
    createdAt = json['createdAt']?.toString();
  }
  String get timeAgo {
    if (createdAt == null) return "";
    DateTime dateTime = DateTime.parse(createdAt!);
    Duration diff = DateTime.now().difference(dateTime);

    if (diff.inDays > 365) {
      return "${(diff.inDays / 365).floor()}y ago";
    } else if (diff.inDays > 30) {
      return "${(diff.inDays / 30).floor()}mo ago";
    } else if (diff.inDays > 0) {
      return "${diff.inDays}d ago";
    } else if (diff.inHours > 0) {
      return "${diff.inHours}h ago";
    } else if (diff.inMinutes > 0) {
      return "${diff.inMinutes}m ago";
    } else {
      return "Just now";
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['receiver'] = receiver;
    data['title'] = title;
    data['body'] = body;
    data['createdAt'] = createdAt;
    return data;
  }
}
