///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PlanModelData {
/*
{
  "planName": "Platinum Plan",
  "subscriptionType": "yearly",
  "subscriptionId": "sub_1ScRLLKlUbZkAAt6NGJgXPju",
  "startDate": "2025-12-09T13:52:43.000Z",
  "endDate": "2026-12-09T13:52:43.000Z",
  "isActive": true,
  "isCancelled": false,
  "price": 300,
  "createdAt": "2025-12-09T13:52:43.407Z"
}
*/

  String? planName;
  String? subscriptionType;
  String? subscriptionId;
  String? startDate;
  String? endDate;
  bool? isActive;
  bool? isCancelled;
  int? price;
  String? createdAt;

  PlanModelData({
    this.planName,
    this.subscriptionType,
    this.subscriptionId,
    this.startDate,
    this.endDate,
    this.isActive,
    this.isCancelled,
    this.price,
    this.createdAt,
  });
  PlanModelData.fromJson(Map<String, dynamic> json) {
    planName = json['planName']?.toString();
    subscriptionType = json['subscriptionType']?.toString();
    subscriptionId = json['subscriptionId']?.toString();
    startDate = json['startDate']?.toString();
    endDate = json['endDate']?.toString();
    isActive = json['isActive'];
    isCancelled = json['isCancelled'];
    price = json['price']?.toInt();
    createdAt = json['createdAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['planName'] = planName;
    data['subscriptionType'] = subscriptionType;
    data['subscriptionId'] = subscriptionId;
    data['startDate'] = startDate;
    data['endDate'] = endDate;
    data['isActive'] = isActive;
    data['isCancelled'] = isCancelled;
    data['price'] = price;
    data['createdAt'] = createdAt;
    return data;
  }
}

class PlanModel {
/*
{
  "status": true,
  "message": "Vendor subscription list",
  "data": {
    "planName": "Platinum Plan",
    "subscriptionType": "yearly",
    "subscriptionId": "sub_1ScRLLKlUbZkAAt6NGJgXPju",
    "startDate": "2025-12-09T13:52:43.000Z",
    "endDate": "2026-12-09T13:52:43.000Z",
    "isActive": true,
    "isCancelled": false,
    "price": 300,
    "createdAt": "2025-12-09T13:52:43.407Z"
  }
}
*/

  bool? status;
  String? message;
  PlanModelData? data;

  PlanModel({
    this.status,
    this.message,
    this.data,
  });
  PlanModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? PlanModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
