///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PushNotificationData {
/*
{
  "_id": "692fe777544d146303be7ca3",
  "title": "gohbfhc",
  "isSheduled": false,
  "sheduledDate": "2025-12-03T00:00:00.000Z",
  "isActive": false,
  "isPublished": false,
  "vendor": "692ee35ba8f4355c9b641236",
  "createdAt": "2025-12-03T07:32:07.797Z",
  "updatedAt": "2025-12-03T08:07:36.734Z"
}
*/

  String? Id;
  String? title;
  bool? isSheduled;
  String? sheduledDate;
  bool? isActive;
  bool? isPublished;
  String? vendor;
  String? createdAt;
  String? updatedAt;

  PushNotificationData({
    this.Id,
    this.title,
    this.isSheduled,
    this.sheduledDate,
    this.isActive,
    this.isPublished,
    this.vendor,
    this.createdAt,
    this.updatedAt,
  });
  PushNotificationData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    title = json['title']?.toString();
    isSheduled = json['isSheduled'];
    sheduledDate = json['sheduledDate']?.toString();
    isActive = json['isActive'];
    isPublished = json['isPublished'];
    vendor = json['vendor']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['title'] = title;
    data['isSheduled'] = isSheduled;
    data['sheduledDate'] = sheduledDate;
    data['isActive'] = isActive;
    data['isPublished'] = isPublished;
    data['vendor'] = vendor;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class PushNotification {
/*
{
  "status": true,
  "message": "Notification list",
  "data": [
    {
      "_id": "692fe777544d146303be7ca3",
      "title": "gohbfhc",
      "isSheduled": false,
      "sheduledDate": "2025-12-03T00:00:00.000Z",
      "isActive": false,
      "isPublished": false,
      "vendor": "692ee35ba8f4355c9b641236",
      "createdAt": "2025-12-03T07:32:07.797Z",
      "updatedAt": "2025-12-03T08:07:36.734Z"
    }
  ]
}
*/

  bool? status;
  String? message;
  List<PushNotificationData?>? data;

  PushNotification({
    this.status,
    this.message,
    this.data,
  });
  PushNotification.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <PushNotificationData>[];
      v.forEach((v) {
        arr0.add(PushNotificationData.fromJson(v));
      });
      data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['data'] = arr0;
    }
    return data;
  }
}
