///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RatingVendor {
/*
{
  "_id": "66615a734bcea93f3056a7c1",
  "name": "Unknown"
}
*/

  String? Id;
  String? name;

  RatingVendor({
    this.Id,
    this.name,
  });
  RatingVendor.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['name'] = name;
    return data;
  }
}

class RatingUser {
/*
{
  "_id": "665ef5bf36c407a0cdb83858",
  "name": "Rob"
}
*/

  String? Id;
  String? name;

  RatingUser({
    this.Id,
    this.name,
  });
  RatingUser.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['name'] = name;
    return data;
  }
}

class Rating {
/*
{
  "_id": "6682aa8d43f918228ed7fd86",
  "user": {
    "_id": "665ef5bf36c407a0cdb83858",
    "name": "Rob"
  },
  "review": "Nice ambience",
  "rating": 5,
  "vendor": {
    "_id": "66615a734bcea93f3056a7c1",
    "name": "Unknown"
  }
}
*/

  String? Id;
  RatingUser? user;
  String? review;
  int? rating;
  RatingVendor? vendor;

  Rating({
    this.Id,
    this.user,
    this.review,
    this.rating,
    this.vendor,
  });
  Rating.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    user = (json['user'] != null) ? RatingUser.fromJson(json['user']) : null;
    review = json['review']?.toString();
    rating = json['rating']?.toInt();
    vendor = (json['vendor'] != null) ? RatingVendor.fromJson(json['vendor']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['review'] = review;
    data['rating'] = rating;
    if (vendor != null) {
      data['vendor'] = vendor!.toJson();
    }
    return data;
  }
}
