///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ScanRedemptionModelData {
/*
{
  "date": "2025-12-11",
  "totalScans": 3,
  "rewardRedeems": 0,
  "stampRedeems": 3
}
*/

  String? date;
  int? totalScans;
  int? rewardRedeems;
  int? stampRedeems;

  ScanRedemptionModelData({
    this.date,
    this.totalScans,
    this.rewardRedeems,
    this.stampRedeems,
  });
  ScanRedemptionModelData.fromJson(Map<String, dynamic> json) {
    date = json['date']?.toString();
    totalScans = json['totalScans']?.toInt();
    rewardRedeems = json['rewardRedeems']?.toInt();
    stampRedeems = json['stampRedeems']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['date'] = date;
    data['totalScans'] = totalScans;
    data['rewardRedeems'] = rewardRedeems;
    data['stampRedeems'] = stampRedeems;
    return data;
  }
}

class ScanRedemptionModel {
/*
{
  "status": true,
  "message": "Datewise loyalty stamp stats",
  "data": [
    {
      "date": "2025-12-11",
      "totalScans": 3,
      "rewardRedeems": 0,
      "stampRedeems": 3
    }
  ]
}
*/

  bool? status;
  String? message;
  List<ScanRedemptionModelData>? data;

  ScanRedemptionModel({
    this.status,
    this.message,
    this.data,
  });
  ScanRedemptionModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ScanRedemptionModelData>[];
      v.forEach((v) {
        arr0.add(ScanRedemptionModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
