///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SubscriptionModel {
/*
{
  "_id": "66b2da0baa2e7f53d408f164",
  "title": "Silver Plan",
  "billedFrequency": "monthly",
  "planType": "subscribers",
  "price": 100,
  "features": [
    "Access to basic analytics"
  ],
  "stripeProdutId": "prod_QcE0CIBE3m3JgJ",
  "stripePriceId": "price_1PkzYNKlUbZkAAt63bH4cqbH",
  "createdAt": "2024-08-07T02:20:59.088Z",
  "updatedAt": "2024-08-07T02:20:59.088Z",
  "__v": 0,
  "isActive": true
}
*/

  String? Id;
  String? title;
  String? billedFrequency;
  String? planType;
  int? price;
  List<String?>? features;
  String? stripeProdutId;
  String? stripePriceId;
  String? createdAt;
  String? updatedAt;
  bool? isActive;

  SubscriptionModel({
    this.Id,
    this.title,
    this.billedFrequency,
    this.planType,
    this.price,
    this.features,
    this.stripeProdutId,
    this.stripePriceId,
    this.createdAt,
    this.updatedAt,
    this.isActive,
  });
  SubscriptionModel.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    title = json['title']?.toString();
    billedFrequency = json['billedFrequency']?.toString();
    planType = json['planType']?.toString();
    price = json['price']?.toInt();
    if (json['features'] != null) {
      final v = json['features'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      features = arr0;
    }
    stripeProdutId = json['stripeProdutId']?.toString();
    stripePriceId = json['stripePriceId']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    isActive = json['isActive'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['title'] = title;
    data['billedFrequency'] = billedFrequency;
    data['planType'] = planType;
    data['price'] = price;
    if (features != null) {
      final v = features;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['features'] = arr0;
    }
    data['stripeProdutId'] = stripeProdutId;
    data['stripePriceId'] = stripePriceId;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['isActive'] = isActive;
    return data;
  }
}
